### ISSUE TITLE
Has anyone been able to start a topic using Docker Compose?

### ISSUE THREAD

**Issue by andrewterra** [spotify/docker-kafka#75]
I attempted to put 

```
kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka
    expose:
      - "9092"
      - "2181"
    environment:
      TOPICS: test-topic
```

But this failed to work, is there something that I'm missing? (I tried with quotes around the topic as well)

Also, if anyone has had any luck using Spring to connect to a topic, I would greatly appreciate some help connecting to the topics.
